---
- name: "Generate Let's Encrypt CSR"
  #shell: "openssl req -new -sha256 -key /etc/letsencrypt/keys/{{ domain_name }}.key -subj \"/CN={{ domain_name }}\" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf \"\n[SAN]\nsubjectAltName=DNS:{{ domain_name }},DNS:www.{{ domain_name }}\")) | tee /etc/letsencrypt/csrs/{{ domain_name }}.csr"
  shell: > 
    openssl req -new -sha256 -key /etc/letsencrypt/keys/{{ item }}.key
    -subj "/CN={{ item }}" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf
    <(printf "\n[SAN]\nsubjectAltName=DNS:{{ item }}"))
    | tee /etc/letsencrypt/csrs/{{ item }}.csr
  args:
    executable: /bin/bash


- name: "Generate Let's Encrypt private key"
  shell: "openssl genrsa 4096 | tee {{ letsencrypt_keys_dir }}/{{ item }}.key"